### ISSUE TITLE
Requests with Stevens as the recipient return a 400

### ISSUE THREAD

**Issue by fbueti** [contracts-go/webapp#1]
idk why :(

**Comment by austince** [comment]
Ah :/ I'll look into it. Sending the same data?

**Comment by fbueti** [comment]
Yes, but don't worry about it! Just bringing it up for next week

-- Checking it out now ! 

-- Also: why can I edit what you say?

**Comment by austince** [comment]
Silly typo: Changed 'recipient' to 'receiving'. Error message was wrong :(
